export const ALREADY_EXISTS_ERROR = 'Such user already exists'
export const NO_USER_FOUND_ERROR = 'Such user was not found'
export const WRONG_PASSWORD_ERROR = 'Wrong password'
export const INVALID_PASSWORD_LENGTH_ERROR = 'The password must be between 5 and 30 characters long'
export const INVALID_TOKEN_ERROR = 'Invalid or expired token'
export const INVALID_ACCOUNT_ACTIVATION_TOKEN_ERROR = 'Invalid or expired account activation token'
export const MISSING_REFRESH_PARAMS_ERROR = 'Missing token or device ID'
export const UNAUTHORIZED_ERROR_MSG = 'Unauthorized'

export const LOGOUT_SUCCESS = 'Successful logout'
export const ACCOUNT_DELETION_SUCCESS = 'Account successfully deleted'
export const PASSWORD_RESET_SUCCESS_MSG = 'Password reset token sent to the email'
export const PASSWORD_UPDATE_SUCCESS_MSG = 'Password update was successful'
