name: Build and deploy Docker app to Azure 
on:
  push:
    branches:
      - main
  workflow_dispatch:

env: 
  REGISTRY: docker.io
  IMAGE_NAME: raymond7510/my-nestjs-api

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node_modules-

      - name: Install dependecies
        run: npm ci

      - name: Test application
        run: npm run test:e2e
      
      - name: Save test report as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ./test-report

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with: 
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AUTH_TOKEN }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps: 
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with: 
          app-name: my-nestjs-api
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

  notify-telegram:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Download a test report artifact
        uses: actions/download-artifact@v3
        with:
          name: test-report
          path: ./report

      - name: Send report to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_API_URL: "https://api.telegram.org"
        run: |
          REPORT_FILE="./report/report.html"

          if [ -f "$REPORT_FILE" ]; then
            curl -F chat_id=$TELEGRAM_CHAT_ID \
              -F document=@"$REPORT_FILE" \
              -F caption="Test report for build: \`${{ github.sha }}\`" \
              -F parse_mode="Markdown" \
              "${TELEGRAM_API_URL}/bot$TELEGRAM_BOT_TOKEN/sendDocument"
          else
            curl -F chat_id=$TELEGRAM_CHAT_ID \
              -F text="Test report not found for build: \`${{ github.sha }}\`" \
              -F parse_mode="Markdown" \
              "${TELEGRAM_API_URL}/bot$TELEGRAM_BOT_TOKEN/sendMessage"
          fi
