name: Run e2e tests and send the report to the Telegram bot
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm ci

      - name: Test application
        run: npm run test:e2e

      - name: Save test report as artifact
        if: always() # Артефакт зберігається незалежно від успіху чи невдачі
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ./test-report

  notify-telegram:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download test report artifact
        uses: actions/download-artifact@v3
        with:
          name: test-report
          path: ./report

      - name: Send report to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -F chat_id=$TELEGRAM_CHAT_ID \
               -F document=@"./report/test-report-file.json" \
               -F caption="Test report for build ${{ github.sha }} - $(date)" \
               "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument"
