name: Run e2e tests and send the report to the Telegram bot

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install dependencies
        run: npm ci

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Save test report as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: ./test-report

  notify-telegram:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download test report artifact
        uses: actions/download-artifact@v3
        with:
          name: test-report
          path: ./report

      - name: Send report to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_API_URL: "https://api.telegram.org"
        run: |
          REPORT_FILE="./report/report.html"

          if [ -f "$REPORT_FILE" ]; then
            curl -F chat_id=$TELEGRAM_CHAT_ID \
              -F document=@"$REPORT_FILE" \
              -F caption="Test report for build: \`$GITHUB_SHA\`" \
              "${TELEGRAM_API_URL}/bot$TELEGRAM_BOT_TOKEN/sendDocument"
          else
            curl -F chat_id=$TELEGRAM_CHAT_ID \
              -F text="Test report not found for build: \`$GITHUB_SHA\`" \
              "${TELEGRAM_API_URL}/bot$TELEGRAM_BOT_TOKEN/sendMessage"
          fi
